//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1st_Program.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int RollNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> Mark1 { get; set; }
        public Nullable<decimal> Mark2 { get; set; }
        public Nullable<decimal> Mark3 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Avg { get; set; }
        public string Res { get; set; }
    }
}
